### ISSUE TITLE
fix generateCipherStream, initialize nonce

### ISSUE THREAD

**Issue by david415** [lightningnetwork/lightning-onion#3]
the nonce isn't set!?
https://github.com/lightningnetwork/lightning-onion/blob/master/sphinx.go#L337-L338

perhaps you could argue that setting the nonce isn't strictly necessary?

**Comment by Roasbeef** [comment]
Technically, the nonce _is_ set, just to an initial value of all zeroes. 

A nonce of all zeros is permissible as each generated intermediate key is _never_ re-used. Within packet generation/processing `chacha20` is used as a CSPRNG to generate a stream of random bytes by running the cipher with a fixed-size byte slice of all zeroes as input. As a result, the nonce is never incremented.

**Comment by david415** [comment]
ok sounds good. sorry for the noise.
