### ISSUE TITLE
Implement error message wraping/encryption and decryption 

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lightning-onion#4]
## Issue
Within the network, it's important that when an HTLC forwarding failure occurs, the recipient is notified in a timely manner in order to ensure that errors are graceful and not unknown. However, we also want to ensure the privacy of the onion routing scheme, meaning that the intermediate hops don't know the exact location of the initiating sender. Therefore, nodes need to use the existing circuit to report the error with a message traveling backwards from the point of error to the original sender. 

Within the current [spec draft](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md) the handling of the scenario described above is detailed in sufficiently in the [returning messages section](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#returning-messages). 

This error wrapping and decryption at the sender is currently unimplemented. 

## Steps to Completion 

- [x] The `ProcessPacket` method should also return an object which encapsulates the derived shared secret, and provides a method/function to create a wrapped error messages. 

- [x] Similarly, the `NewOnionPacket` function should return a similar object which encapsulates the derived shared secret, and the encoded route. The object should provide a method/function to perform trial decryption (`O(N^2)` work, since we don't know which node in the route send the message).

**Comment by BitfuryLightning** [comment]
Will take this one.

**Comment by Roasbeef** [comment]
Closed by #8.
