### ISSUE TITLE
CHDR introducing version

### ISSUE THREAD

**Issue by andbene72** [lightningnetwork/lightning-onion#5]
Hi Roastbeef,

Although in the original paper is not expected, IMHO it would be appropriate to add a byte at the beginning of Common header to be used to versioning the Hornet protocol (as indeed exists in the IP protocol). My proposal is:

| Bit | 0-3     | 4-7      | 8-15         | 16-23 | 24-             |
| -----| ---------| ----------| --------------| -------| -----------------| 
| 0   | Version | Future Uses | Control Type | Hops  | ...             |

Andrea

**Comment by EvertonMelo** [comment]
@Roasbeef @cdecker 

What is described above proceeds?
I found no evidence of this.
